### ISSUE TITLE
DirectX 12 does not work with Lutris Wine 6.13-3 in some distributions

### ISSUE THREAD

**Issue by SwimmingTiger** [lutris/wine#101]
I installed the Battle.net client via https://lutris.net/games/battlenet/, but I don’t see the DirectX 12 option in World of Warcraft.

I noticed that it is using wine lutris-6.13-3. I tried to switch the wine version to the following version, but the DirectX 12 option still did not appear.
* lutris-6.13-3
* lutris-6.10-7
* lutris-6.10-6

When I switched the wine version to lutris-6.4, the DirectX 12 option appeared in World of Warcraft and worked well.

In addition, lutris-6.13-3 cannot run Cyberpunk 2077 and Assassin's Creed Valhalla. Both of these are DirectX 12 only games.

The DXVK/VKD3D option is enabled. The DXVK version is v1.9.1L.

```
[System]
OS:              Deepin 20.2.2 n/a
Arch:            x86_64
Kernel:          5.10.36-amd64-desktop
Desktop:         Deepin
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.57.02
OpenGL Core:     4.6.0 NVIDIA 470.57.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.57.02
Vulkan:          Supported
```

**Comment by tannisroot** [comment]
I cannot reproduce these issues, DirectX 12 works fine for me, on Nvidia.

**Comment by SwimmingTiger** [comment]
I switched to Ubuntu 20.04, and then DirectX 12 in Lutris Wine 6.13-3 worked fine. It looks like this is a distribution specific issue. I will continue to study and add details.

**Comment by YihaoPeng** [comment]
I found that it might be an upstream issue. Because in my distribution, all official wine staging releases since winehq-staging 6.9 cannot work with VKD3D-proton normally.

**Comment by YihaoPeng** [comment]
The cause of this problem may be the outdated version of `libvulkan1`.

`Deepin 20.2.2` has `libvulkan1` `1.1.97` and then vkd3d-proton no longer works in wine 6.9 and later versions.

`Ubuntu 20.04` has `libvulkan1` `1.2.131` and vkd3d-proton and DX12 work well.

**Comment by tannisroot** [comment]
Oh yeah there is no way DX12 will work this vulkan this ancient.
