### ISSUE TITLE
Battle.Net install error

### ISSUE THREAD

**Issue by DocMAX** [lutris/wine#102]
![grafik](https://user-images.githubusercontent.com/5351323/128467411-91a1af93-591b-42c3-8bcd-963cf7254fcf.png)

**Comment by tannisroot** [comment]
I can't help when there's no useful information to work with

**Comment by DocMAX** [comment]
Sorry i though you guess it. It come when installing Battle-Net via Lutris.

**Comment by tannisroot** [comment]
Can you join the Lutris discord server, go to lutris-support, type in `!log`, follow the instructions and ping me there (i have the same name)?
