### ISSUE TITLE
League On Manjaro script is broken

### ISSUE THREAD

**Issue by ChillSheep** [lutris/wine#117]
Describe the bug

Install script for League of Lutris is broken on Manjaro KDE Plasma.

Expected behavior

A successful and running LoL installation.

Current behavior
Installing works fine until the client opens, where it will stay black for an indefinite amount of time, killing the process will lead to the following result:
League folder stays empty after installation. Trying to start league says "LeagueClient.exe could not be found"

Steps to reproduce
Install League over the Installer Script https://lutris.net/games/league-of-legends/

**Comment by GloriousEggroll** [comment]
This is resolved. League now requires using the Riot Client. I've changed the script to use the Riot Client, as well as the instructions on the page.
