### ISSUE TITLE
controller doesn't work when pluging/unpluging in game 

### ISSUE THREAD

**Issue by aymanred121** [lutris/wine#118]
when detaching and reattaching the controller it doesn't register and I have to restart the game in order the make them work again.
this issue is present on any Lutris-wine > Lutris-6.4

**Comment by tannisroot** [comment]
Which game and what controller

**Comment by aymanred121** [comment]
nearly all games (except for hades)
controller: Logitech Gamepad F310 in xinput mode

**Comment by tannisroot** [comment]
Please retest with 6.21

**Comment by aymanred121** [comment]
I can confirm that it's indeed fixed in 6.21
