### ISSUE TITLE
Color issues in games with Lutris fshack builds

### ISSUE THREAD

**Issue by keenanweaver** [lutris/wine#119]
I've noticed some color issues in games. The closest report I've seen that accurately describes the issue is this: https://www.reddit.com/r/linux_gaming/comments/qpg4l6/deus_ex_goty_via_steamplay_runs_in_deepfried_mode/

Some games I've tested are Silent Hill 4, Freelancer, and Hitman: Contracts. Not sure what the commonality is between them besides being old. Looks like it's a [consequence of the fullscreen hack](https://github.com/ValveSoftware/Proton/issues/798#issuecomment-489275416).

Here are some screenshots of the issue

Issue:
![2021-11-15_07-25](https://user-images.githubusercontent.com/37268985/141797591-5eb2ed39-715a-4067-90aa-4d41ea67a9c6.png)
Correct:
![2021-11-15_07-22](https://user-images.githubusercontent.com/37268985/141797597-3b90d75c-2ae7-4998-9ec8-6fe0da11e5e4.png)

Issue:
![2021-11-15_08-17](https://user-images.githubusercontent.com/37268985/141797600-73378329-aa37-4d03-828f-ee5d9c8770cc.png)
Correct:
![2021-11-15_08-19](https://user-images.githubusercontent.com/37268985/141797601-ec246b6c-05d1-424e-a77e-f99d28ee841b.png)

Issue does not happen in the Lutris non-fshack builds and Lutris fshack builds before 6.10. For additional context, it also does not happen for Wine Staging 6.21 and the Wine-GE 6.21 builds. 

Doing the workaround in the link above fixes the issue, but also messes up brightness on any secondary monitor. 

I don't think this is an issue for Lutris to resolve, per se, but just wanted to note it down since it is an issue that persists with the latest Lutris fshack builds.

**Comment by tannisroot** [comment]
I think I know what this is, let me cook a test build in a few minutes.

**Comment by tannisroot** [comment]
Try this build please https://drive.google.com/file/d/1fXF2zz3OPmztdL8ZVpa2KeB1c8-DH7Cw/view?usp=sharing

**Comment by keenanweaver** [comment]
> Try this build please https://drive.google.com/file/d/1fXF2zz3OPmztdL8ZVpa2KeB1c8-DH7Cw/view?usp=sharing

Works as expected! Thank you very much!
