### ISSUE TITLE
At least 3 games (from epic games store) will not join network games

### ISSUE THREAD

**Issue by eclass4learning** [lutris/wine#127]
Greetings everyone!

I am running latest lutris + wine-lutris-6.10.7 on an archlinux install using kernel 5.10 (lts)

on winelutris 6.10.7 i can join and be joined on online games

bu starting on wine lutris 6.13.3 i can no longer join or be joined with on online games. The game will try for a while to join but then fail.

The rest of the game(s) work fine, its just the online part that seems to be somehow not working.

The games i play the most, on which i experience this problem are borderlands3, remnant from ashes and civilization VI. ALl of them from the epic store.

Has anyone experienced this problem ? any advise?

**Comment by tannisroot** [comment]
Have you tried with lutris-6.21?

**Comment by eclass4learning** [comment]
> Have you tried with lutris-6.21?

Yes, same problem

**Comment by tannisroot** [comment]
Could you message me on Lutris Discord? I am willing to bisect the issue.

**Comment by eclass4learning** [comment]
> Could you message me on Lutris Discord? I am willing to bisect the issue.

Of course, how should i find you over there ?, not very familiar with Discord

**Comment by tannisroot** [comment]
Join the Lutris Discord server and I will be listed on the right as Tannis Root

**Comment by eclass4learning** [comment]
> 

Gotcha, c ya there!
