### ISSUE TITLE
6.21 wont run on x86_64

### ISSUE THREAD

**Issue by axet** [lutris/wine#128]
Hello!

Recent lutris 6.21-6 wine release work twice (!!!) as fast on x32 prefixes and unable to start any x64 prefixes (in compare to 6.14-4).

Nothing helping: creating new clean prefixes, checking filesystem.

Same prefixes works fine with 6.14-4 or even winehq-6.21. If I switch to 6.21-6 x86_64 prefixes are freeze at start unless I turn off network?! Then after game starts resuming network - makes everything works fine (and faster then on windows!!!)

Looks like freezing is network related issue. Freeze message is common:

```
0024:err:environ:run_wineboot boot event wait timed out
```

and a lot of wineboot output like:

```
0054:err:sync:RtlpWaitForCriticalSection section 000000007BC6C640 "/home/ubuntu/buildbot/runners/wine/wine-src/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0054, blocked by 0050, retrying (60 sec)
0060:err:sync:RtlpWaitForCriticalSection section 000000023D8FB140 "/home/ubuntu/buildbot/runners/wine/wine-src/dlls/user32/user_main.c: user_section" wait timed out in thread 0060, blocked by 0040, retrying (60 sec)
0054:err:sync:RtlpWaitForCriticalSection section 000000007BC6C640 "/home/ubuntu/buildbot/runners/wine/wine-src/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0054, blocked by 0050, retrying (60 sec)
0060:err:sync:RtlpWaitForCriticalSection section 000000023D8FB140 "/home/ubuntu/buildbot/runners/wine/wine-src/dlls/user32/user_main.c: user_section" wait timed out in thread 0060, blocked by 0040, retrying (60 sec)
0054:err:sync:RtlpWaitForCriticalSection section 000000007BC6C640 "/home/ubuntu/buildbot/runners/wine/wine-src/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0054, blocked by 0050, retrying (60 sec)
0060:err:sync:RtlpWaitForCriticalSection section 000000023D8FB140 "/home/ubuntu/buildbot/runners/wine/wine-src/dlls/user32/user_main.c: user_section" wait timed out in thread 0060, blocked by 0040, retrying (60 sec)
0054:err:sync:RtlpWaitForCriticalSection section 000000007BC6C640 "/home/ubuntu/buildbot/runners/wine/wine-src/dlls/ntdll/loader.c: loader_section" wait timed out in thread 0054, blocked by 0050, retrying (60 sec)
0060:err:sync:RtlpWaitForCriticalSection section 000000023D8FB140 "/home/ubuntu/buildbot/runners/wine/wine-src/dlls/user32/user_main.c: user_section" wait timed out in thread 0060, blocked by 0040, retrying (60 sec)
```

I able to start x86_64 wine only with wifi disabled... Seems like some network activity preventing wine to start or create prefix...

Is here a virus?

I did some tests with 'strace' and got following logs:

```
writev(3, [{iov_base="\33\0\0\0000\0\0\0\0\0\0\0\2\0\0\0\324\244\303\377\0\0\0\0\251\7Q=\367\377\377\377"..., iov_len=64}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., iov_len=40}, {iov_base="\1\0\0\0\4\0\0\0", iov_len=8}], 3) = 112
read(5, "\3\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 64) = 64
rt_sigprocmask(SIG_SETMASK, [HUP INT USR1 USR2 ALRM CHLD IO], NULL, 8) = 0
read(7,
```

Where 7 file number is defined as pipe:

```
pipe2([5, 6], O_CLOEXEC)                = 0
pipe2([7, 8], O_CLOEXEC)                = 0
```

Full logs of `WINEPREFIX=$PWD/123 strace --output=123.log ~/.local/share/lutris/runners/wine/lutris-6.21-6-x86_64/bin/wineboot ` attached.

**Comment by axet** [comment]
[123.txt](https://github.com/lutris/wine/files/7702875/123.txt)

**Comment by tannisroot** [comment]
Can you reproduce this with wine ge? https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/6.21-GE-1

**Comment by axet** [comment]
Works fine

**Comment by axet** [comment]
First run works, second run wine-ge fails.

Original directory with wine-ge unchanged.

**Comment by tannisroot** [comment]
Can you see if Wine-Staging 6.21 works reliable as well?

**Comment by axet** [comment]
OK. winehq-6.21 failing on second run with following:

```
axet@axet-laptop:~$ poe
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
**double free or corruption (out)**
00d0:err:sync:RtlpWaitForCriticalSection section 000000007BC64600 "dlls/ntdll/loader.c: loader_section" wait timed out in thread 00d0, blocked by 00c0, retrying (60 sec)
```

**Comment by tannisroot** [comment]
What distribution are you on?

**Comment by axet** [comment]
debian 12 bookworm

**Comment by tannisroot** [comment]
Are you able to install older wine-staging version on Debian easily? For regression testing purposes

**Comment by axet** [comment]
Yes. I wrote helping wrapper, which can select any version easily:

* https://gitlab.com/axet/homebin/-/tree/debian/winehere

**Comment by tannisroot** [comment]
Can you test versions between 6.14 and 6.21 to determine in which one the issue first appeared? Make sure to account for breakage on second launch.

**Comment by axet** [comment]
They all working fine. I ran twice each.

**Comment by axet** [comment]
winehq-6.22 works fine. Twice run. Worth rebasing?

**Comment by axet** [comment]
I found what is causing it. Very strange.

Having those files in ~/.cache/AMD/VkCache directory causing wine to crash with double corrupt message:

A21E3B76F983AB25CAD2A47E19EFB13B_1.parc  A21E3B76F983AB25CAD2A47E19EFB13B_4.parc  A21E3B76F983AB25CAD2A47E19EFB13B_7.parc  A21E3B76F983AB25CAD2A47E19EFB13B.parc
A21E3B76F983AB25CAD2A47E19EFB13B_2.parc  A21E3B76F983AB25CAD2A47E19EFB13B_5.parc  A21E3B76F983AB25CAD2A47E19EFB13B_8.parc
A21E3B76F983AB25CAD2A47E19EFB13B_3.parc  A21E3B76F983AB25CAD2A47E19EFB13B_6.parc  A21E3B76F983AB25CAD2A47E19EFB13B_9.parc

I guess I'm using AMD video card with (amdvlk:amd64 2021.Q4.2) installed from official repository.

It is lutris-6.21-6 dependent (or any wine).

files:

* https://disk.yandex.ru/d/ZmIVKwyNbuTDiQ

AMD video driver:

* https://github.com/GPUOpen-Drivers/AMDVLK

**Comment by tannisroot** [comment]
Please do not use AMDVLK driver, just uninstall it and use plain mesa. AMDVLK is a lot buggier and slower than radv from mesa.

**Comment by axet** [comment]
I'l try mesa one. Looks similar...

But reinstalling AMDVLK cauing this "wired" cache appear again in smaller size (10M) and cusing corruption again

* https://disk.yandex.ru/d/vXEmUl5DAVjGFg

**Comment by tannisroot** [comment]
Please just uninstall AMDVLk.

**Comment by axet** [comment]
Ok. I saved those files in cache folder. In case this is a virus.

**Comment by tannisroot** [comment]
It's not a viruses, those are probably just shader cache files.
