### ISSUE TITLE
God Of War: Shuttering with "low" GPU usage.

### ISSUE THREAD

**Issue by nitanmarcel** [lutris/wine#132]
My GPU is slow, I have a GTX 1060 Mobile 4GB VRAM and I get 99% GPU usage all the time even on lower with FSR enabled.

But that's not the main problem. The main problem is that I get lower GPU usage but when that happens my game starts running at -20 fps opposite to 40-80 which I get when the GPU is used at high speed.

Mostly this happens when an effect is played. And what I can say is that it's not from my GPU because using wine-ge-custom the shuttering doesn't happen so often. An example is when at the start of the game Kratos cuts the tree down and when it hits the ground the game dropped in FPS with lutris-wine and lutris-wine-fshack (doesn't happen with wine-ge-custom)

**Comment by tannisroot** [comment]
Could you provide me with a performance recording of some sort of built in benchmark using MangoHud, with lutris-fshack and wine-ge-custom? Also please specify which versions you are using

**Comment by nitanmarcel** [comment]
With both I was getting the same result but it looks like dxvk was the problem. I installed the dxvk-master version and the shuttering is gone and the game is stabler than it was before.

I can still get the benchmark if you need it. :)

**Comment by nitanmarcel** [comment]
Closing this as the game stability improved after using the master version of dxvk.

As the moment of this comment the dxvk repo has these commits for God Of War:

[[util] Enable performance options for God of War ](https://github.com/doitsujin/dxvk/commit/42c06ceb51dcce591981ee3b90d63ea265448e1f)
[[util] Disable NVAPI hack for God of War ](https://github.com/doitsujin/dxvk/commit/703cc78cc01429e7079282451bbdec10bdb1e245)

**Comment by tannisroot** [comment]
Thanks, I will need to update DXVK then.
