### ISSUE TITLE
Wine 7.0 build

### ISSUE THREAD

**Issue by MrMEEE** [lutris/wine#134]
Hi

For several older titles, this black box cursor is an issue:

https://bugs.winehq.org/show_bug.cgi?id=51296

This is fixed in Wine-7.0-rc2..

Wine 7.0 is now GA.. Is there an estimate for a build in Lutris?

**Comment by tannisroot** [comment]
It's coming

**Comment by liberodark** [comment]
Is better to wait for 7.2 is adding first wma support.

**Comment by runboy93** [comment]
> Is better to wait for 7.2 is adding first wma support.

7.2 just started work for wma support, step by step. Might take "few" more releases for full wma support.

**Comment by tannisroot** [comment]
We will have full wma audio support in Lutris Wine because we still use faudio-side wma decoding.

**Comment by runboy93** [comment]
> We will have full wma audio support in Lutris Wine because we still use faudio-side wma decoding.

I'm bit confused about this, I thought that faudio used GStreamer for wma decoding, yet on faudio 22.02 changelog it says:

GStreamer support has been removed
Wine/Win32 will continue to use MediaFoundation
All other users should already be on patent/royalty-free codecs

And GE released this earlier:
https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/7.1-GE-2

I'm just missing important point?

**Comment by tannisroot** [comment]
Yes we hotfix it to bring it back
