### ISSUE TITLE
Overwatch: Compiling shaders...

### ISSUE THREAD

**Issue by superbonaci** [lutris/wine#14]
When I run overwatch on lutris it says "Compiling shaders..." for a while. Happens every time I start the game on Lutris, but not on Windows 10. It's not a big issue because the game still works well, but maybe there is some issue.

![Overwatch displaying Compiling shaders...](https://i.imgur.com/DFSFqyn.jpg)

**Comment by superbonaci** [comment]
> I ran into this too, weather it is set to 0 or 1 does not matter. You have a remove the define all together to turn it off to test.

Tried removing the var and makes no effect, about 20-ish seconds. I remember weeks ago it took 10 or 15 minutes to finish. By the way I added another bug to allow enable/disable or vars without having to actually remove them to try

https://github.com/lutris/lutris/issues/2482

**Comment by qwertysam** [comment]
I currently run into this problem on Ubuntu 18.04 with the NVIDIA 440 driver. It takes about 15minutes to compile each time I start up overwatch, and then it's fine from them.

**Comment by superbonaci** [comment]
@qwertysam ubuntu 18.04 is quite old if you want bleeding edge support. Why don't you update to 19.10?

**Comment by dyeray** [comment]
I'm also hitting this bug after getting a new laptop with a GTX 1660+AMD (nvidia prime) and the 440 driver on Ubuntu 19.10. It was working fine on my previous laptop which I believe never was updated to 440 driver although I could be mistaken. With the previous laptop I also had shader compilation stuttering at some point, but was solved with the skip cleanup option, the option seems to be useless now, and I get the shaders compiling + 10 FPS every time I start the game.

I've there's logs needed to investigate this I'm happy to help.

**Comment by tannisroot** [comment]
The issue is with 440 driver. Nvidia will be rolling out a new release by the end of this year with the fix. For now, rollback to the previous driver series, like 435 or 430.
