### ISSUE TITLE
HID device with more than 8 axis breaks wine/lutris runners

### ISSUE THREAD

**Issue by MNS26** [lutris/wine#167]
earlier today i found a reliable way to break wine using a HID device with 9 axis, 
if i kept it at 8 nothing freaks out but adding the 9th one made it spam buttons (that werent actually pressed)

i also made a wineHQ bug and got a .patch file from `Rémi Bernon` [bus_sdl.c patch](https://bugs.winehq.org/attachment.cgi?id=75417&action=diff&context=patch&collapsed=&headers=1&format=raw) (cant send file directly since its not supported) that fixes it 
from what it looks it is overwriting the buttons after the axis 

wineHQ [HID with more than 8 axis overwrites inputs after it](https://bugs.winehq.org/show_bug.cgi?id=55660)

9 axis without patch
![image](https://github.com/lutris/wine/assets/53867268/5031aeeb-c74b-4d0d-866f-a4f2269b757d)

8 axis without patch
![image](https://github.com/lutris/wine/assets/53867268/762c876f-4317-4d8e-a1f3-96082deaad21)

9 axis with patch
![image](https://github.com/lutris/wine/assets/53867268/aed89e79-8d1d-4e59-9bce-f3d839321842)

**Comment by GloriousEggroll** [comment]
The patch provided was authored by rbernon, who handles HID device + controller input for wine and proton. Since it's confirmed working it will make it's way into proton soon and subsequently wine + proton-ge. I'll add the patch until it's upstreamed.

**Comment by MNS26** [comment]
i will close it then, kinda forgot about it.
