### ISSUE TITLE
Lutris won't install Origin correctly

### ISSUE THREAD

**Issue by LowlyDev** [lutris/wine#17]
When trying to install origin with lutris, it "installs", but then gives the message that the exe file cannot be found and some parts of the installation might not be complete, when I check the folder there is no exe file, and so obviously I cannot run it. Does anyone know how to fix this?

**Comment by tannisroot** [comment]
Have you followed instructions listed on this page? https://github.com/lutris/lutris/wiki/Wine-Dependencies

**Comment by LowlyDev** [comment]
yes, sorry for the late reply, it still doesn't work, I get the same error
