### ISSUE TITLE
Lutris doesn't install games/programs correctly

### ISSUE THREAD

**Issue by LowlyDev** [lutris/wine#18]
Trying to install any program with lutris it doesn't add any of the executable files, and gives the error "no file provided" (for obvious reasons) when trying to launch. I have tried reinstalling wine and lutris, followed the dependencies instructions, and tried other programs. Yet I can't seem to get lutris to install programs, anyone know what's wrong?

**Comment by tannisroot** [comment]
Do you have all dependencies installed?
