### ISSUE TITLE
Overwatch: lutris-5.0 does not detect high refresh rate screen

### ISSUE THREAD

**Issue by superbonaci** [lutris/wine#20]
My screen can display up to 120Hz, with `lutris-4.13-x86_64` runner I get top FPS, however with newer version `lutris-5.0-x86_64 (default)` I only can configure video settings inside Overwatch to 50FPS@FHD.

Lutris 4.13:
![Lutris 4.13](https://i.imgur.com/sQYa6aq.png)

Lutris 5.0:
![Lutris 5.0](https://i.imgur.com/G7iWowb.png)

Everything else is just exactly the same.

**Comment by superbonaci** [comment]
Ok no developer can check this?

**Comment by JanGalek** [comment]
@superbonaci I would like check this, but I don't have monitor with 120Hz+ now.

**Comment by superbonaci** [comment]
@JanGalek ok if there's anything I can do...

**Comment by superbonaci** [comment]
Issue still happening with `lutris-5.2-x86_64`

**Comment by superbonaci** [comment]
Based on other people's feedback, latest version which will work with 120Hz refresh rate is `lutris-4.16-x86_64`

**Comment by superbonaci** [comment]
Issue still happening with `lutris-5.4-x86_64`

**Comment by Yjnar** [comment]
I have almost the exact same GPU (1080 ti) with 3 monitors attached (1 HDMI, 2 DP), one being a 165hz monitor, I have no issues with refresh rate settings in Overwatch.

**Comment by superbonaci** [comment]
> I have almost the exact same GPU (1080 ti) with 3 monitors attached (1 HDMI, 2 DP), one being a 165hz monitor, I have no issues with refresh rate settings in Overwatch.

My monitor is laptop built-in.

**Comment by superbonaci** [comment]
Still happening with `lutris-5.4-x86_64`

**Comment by superbonaci** [comment]
Still happening with `lutris-5.5-2-x86_64`.

**Comment by superbonaci** [comment]
Works perfectly fine with `lutris-fshack-5.7-x86_64`, with minor slowdowns.

**Comment by superbonaci** [comment]
Now working with `lutris-5.6.2-x86_64`

**Comment by superbonaci** [comment]
Not working either with `lutrix-5.7-x86_64`

**Comment by superbonaci** [comment]
Now working with runner `lutris-5.7-11-x86_64`. At 1920x1080 only allows 50Hz, and maximum is 1024x768@57Hz.

**Comment by superbonaci** [comment]
Latest working perfectly fine is `lutris-fshack-5.7-x86_64`.
