### ISSUE TITLE
World of Warcraft DirectX12 Problems

### ISSUE THREAD

**Issue by Kirotay** [lutris/wine#28]
Hello guys,

First of all.. sorry for my bad english. :)

Since Lutris 0.5.6-1 I've got performance issues with DirectX 12 in World of Warcraft. My FPS dropped to the half of my average FPS in WoW (In Lutris 0.5.5 ~144-160FPS with DX12 - now 60-77 FPS with DX12). The loading time is beyond the 30 seconds mark (even with tweaks, WoW Cache from the git etc..).

If I switch to the DX11 version, everything is fine. Even if I switch to the 0.5.5 Lutris client, the DX12 version of WoW works fine. I've only got the problems with Lutris 0.5.6.

I've reproduced the problem with Ubuntu 19.10/20.04/Pop_OS!, Manjaro, Fedora.

Further Sepc-Information:

GPU: NVIDIA GTX 1080 (Nvidia 440.82)

CPU: I7-8700K

Edit: Used different Lutris wine versions (5.6, 5.7, 5.5, 5.4). None of these versions fixed the problem.

**Comment by derbrachialist** [comment]
It seems to be a cpu issue: https://imgur.com/a/B7Q8OwS
Lutris 0.5.6 only uses 1 core at a time and 0.5.5 uses all cores.

**Comment by Kirotay** [comment]
The Problem exists with Lutris 0.5.7 either.

Ingame FPS with DX12 improved by 5-10 FPS but still way below the DX11 performance. 

Tested with:
GPU: NVIDIA GTX 1080 (Nvidia 440.100 + 450.57)
CPU: I7-8700K
OS: Arch, Fedora, Ubuntu
DXVK Version: 1.6 + 1.7
Wine Version: Lutris-5.5, Lutris-5.6, Lutris-5.7

**Comment by tannisroot** [comment]
Recheck with 6.0-rc1.

**Comment by CDAGaming** [comment]
@tannisroot While I couldn't reproduce the cpu issue, the FPS is far lower so far for 6.0, then it had been in 5.21 when it was up
