### ISSUE TITLE
Origin Launcher EACoreServer.exe && Activation.exe bugz

### ISSUE THREAD

**Issue by ksaadDE** [lutris/wine#31]
I know it doesn't really belong to lutris, but I think here is it also good placed.

Problem:
After Downloading for example BF1 or BF3 the can't be started due to "License Reactivation" stuff.
It just says "Hey dude, enter your serial number or gtfo", it also reports your Origin Account Name as "empty" or "DisplayName".
After entering your serial number or logging in it just says... "bro EA is down, sorry for that" - then welcome in the endless loop.

So basically one of these two Executables getting the things into trouble:
1. EACoreServer.exe 
2. Activation.exe

Also two Webservers having the JSON stuff for the Activation:
1. https://river.data.ea.com
2. https://eaproxy.. blah (don't remember it anymore, just do a quick Wireshark on it, then you will see it)

What I've tried:
Internet Explorer: checking if the Domain works, if connectivity is good..
Origin: Deactivating Ingame-Launch, Deactivate Auto-Update, Activate Beta etc. (literally Everything --_-- )

Maybe you have some fix for that issue, but I couldn't find anything in the Internet (tried every search engine, even chinese ones and so on), would be nice to know. Or maybe I am the only stupid guy here having that issue, then just drop it :> 

Greetz!

**Comment by ksaadDE** [comment]
**Tried all of them ... nothing works!** But it's a bit faster, tried also the .deb Image
It sucks!

**Btw... The Origin Clients connects to some Chinese IPv4:**
![image](https://user-images.githubusercontent.com/37943746/87236385-77e3ee00-c3d8-11ea-8a52-e9fab1258d7d.png)
![image](https://user-images.githubusercontent.com/37943746/87236386-7d413880-c3d8-11ea-8b92-a1baecb71f8f.png)



Another User has also that issue, related to the Origin Client itself:
https://answers.ea.com/t5/Technical-Issues/quot-Connecting-to-Online-Services-quot-is-still-a-problem/td-p/7411907

**Comment by ksaadDE** [comment]
Recorded a example for Bf3 (it's the same Error) https://streamable.com/a1rqx9

**Comment by strycore** [comment]
would you be able to test with a VPN by any chance?

**Comment by ksaadDE** [comment]
@strycore didn't worked either... -_-

Okay now I am out of options.

**Comment by JanGalek** [comment]
This was fixed in Proton: https://github.com/ValveSoftware/Proton/releases/tag/proton-5.0-9

**Comment by ksaadDE** [comment]
@JanGalek I'll test it when I've time. Hopefully it works then, would be awesome!
Thanks for the notice! <3

Have a good time, happy developing
