### ISSUE TITLE
Zwift RunFromProcess "cannot find the specified process"

### ISSUE THREAD

**Issue by TotoVelocipede** [lutris/wine#32]
Hello,

I am an humble Ubuntu end-user, not a coder, attracted by the open and fair numeric world. But I am also a cycling rider ! I wanted to get Zwift running on my Ubuntu 18.04.4 LTS. I found out your Lutris program. I followed all the steps, even the additional installation of Vulkan. I updated & upgraded my packages afterwards, and rebooted. 

Then I followed the last step described on Lutris installation notice:
Zwift requires the launcher to be running at all times. Select "Run EXE inside wine prefix" and select "drive_c/Program Files (x86)/Zwift/ZwiftLauncher.exe". Once it's running you can hit "Play".

But it won't play anything, instead I get a wine warning pop-up:
    + title: RunFromProcess
    + statement:  "cannot find the specified process"

Any idea what's going on? After clicking "OK" nothing would happen and obviously, Zwift doesn't launch.

Cheers

**Comment by tannisroot** [comment]
Recheck with 6.0-rc1.
