### ISSUE TITLE
lutris-* wine packages regression with NFS: Shift 2 Unleashed

### ISSUE THREAD

**Issue by yagoplx** [lutris/wine#33]
When using any lutris-* wine package to play Need For Speed Shift 2 Unleashed, the game will run fine until you start a race. Right before the green light is turned on the physics engine will freeze and everything will become unresponsive and frozen except for the game UI. The game will crash if you continue waiting.

This only happens if, and only if:
You are running any lutris-* wine package
You are using DXVK (tested w/ 1.7.1L-743f309 only)

This does not happen if:
You are using wine-staging from the system
You are using tkg-* wine packages

Tested on:
Pascal Nvidia GPU, proprietary driver
Skylake Intel CPU

**Comment by tannisroot** [comment]
Recheck with 6.0-rc1.
