### ISSUE TITLE
Why our Wine builds are lagging the official Wine releases.

### ISSUE THREAD

**Issue by mpalermo73** [lutris/wine#34]
This wine version is getting very far behind winehq's.  wine is on 5.17 as of this typing.

https://www.winehq.org/announce/5.17

I've been reading the changelogs along with the versions and there looks to be a _considerable_ amount of work getting put in to optimizing and streamlining.  I'm curious why this wine is so far behind.

Thank you.
M.

**Comment by strycore** [comment]
@GloriousEggroll or @tannisroot could you explain in detail the blockers keeping us from pushing current wine releases?
I know it has something to do with esync but I don't have any more details other than "it breaks a bunch of stuff".

**Comment by tannisroot** [comment]
At this point it's just esync.
Initially, it was also due to a fuck ton of regressions caused by NTDLL refactoring, but it has stabilized since.
But because NTDLL code is much different now than in versions like 5.7 (what we currently use), Esync, which was always just a massive patchset, has become incompatible with it and requires a rewrite, so since 5.10, the staging patchset for it has been disabled. I've been told by Zebediah, the author of the patchset, that the write is in progress and it's being tested, but he doesn't really want to guess when it will be finished and publicly released.
As soon as it does, I will release a Lutris build made against a newer Wine version.
In the meantime, I try my best to backport various game fixes and patches from upstream and elsewhere to ensure best possible compatibility with most games. If there's some game that works with newer Wine but not our 5.7 build, let me know and I will see what can be done.

**Comment by mpalermo73** [comment]
@tannisroot 

Thank you for the for the very informative reply.  I have a much better understanding of what is going on behind the scenes now.  I have indeed been keeping up with your patch bumps of `5.7`.  I just keep checking to see if the minor has gotten above `7` yet and now I get why it hasn't.

I pretty much only play World of Warcraft which has ran pretty well under wine for many many years (with some hiccups here and there...).  With a major expansion coming up [at the end of October](https://worldofwarcraft.com/en-us/shadowlands), there's always the chance that something will be broke.  

This is why I'm asking about newer wine builds to better understand how far back "we are" from any possible releases, should WoW be broke and need something newer than 5.7 to run - which unfortunately is likely.

**Comment by tannisroot** [comment]
> With a major expansion coming up at the end of October, there's always the chance that something will be broke.
Oh yeah, I haven't figured out how to backport the fix for WoW to 5.7, so lets hope we will have esync by then.

**Comment by mpalermo73** [comment]
> Oh yeah, I haven't figured out how to backport the fix for WoW to 5.7, so lets hope we will have esync fixed by then.

![mickey](https://user-images.githubusercontent.com/847259/93471118-efdf0080-f8c0-11ea-9bf7-c8f7876141d1.gif)

**Comment by mpalermo73** [comment]
> > With a major expansion coming up at the end of October, there's always the chance that something will be broke.
> 
> Oh yeah, I haven't figured out how to backport the fix for WoW to 5.7, so lets hope we will have esync fixed by then.

Well, Shadowlands (the expansion's title) has been pushed back to an unknown date, but the pre-patch landed today.  My Warcraft either crashes with "windows" access violations, or the screen simply stops repainting but doesn't actually crash.

What do you need from me?
Is there an ETA on this patch making it into lutris' wine 5.7 (or wine itself being upgraded)?

Linux Mandriva (pretty much same as arch) 5.8.11-1
lutris 0.5.7.1
wine 5.7-10
nvidia 450.66

**Comment by mpalermo73** [comment]
> > With a major expansion coming up at the end of October, there's always the chance that something will be broke.
> 
> Oh yeah, I haven't figured out how to backport the fix for WoW to 5.7, so lets hope we will have esync fixed by then.

Well, Shadowlands has been pushed back, but the pre-patch landed today.  My Warcraft install either crashes with "Windows" access violations or freezes (login screen sound keeps playing but screen stops repainting).  

What do you need from me?
Is there an ETA on the patch you mention making it into current Lutris Wine (or wine being upgraded)?

Linux Mandriva (pretty much arch) 5.8.11-1
nvidia 450.66
Lutris 0.5.7.1
wine 5.7-10

**Comment by tannisroot** [comment]
I guess I will need to publish Wine 5.19 without esync...

**Comment by mpalermo73** [comment]
> I guess I will need to publish Wine 5.19 without esync...

Just for grins, I installed wine-staging 5.17.2 from the Manjaro (arch) repo...  and everything Just Works.  My FPS is actually quite good despite no esync(?)

**Comment by strycore** [comment]
I would be interested to have a build of the current wine as well just so I can check if the lack of esync is indeed a big issue.

**Comment by mpalermo73** [comment]
> I would be interested to have a build of the current wine as well just so I can check if the lack of esync is indeed a big issue.

All I can say after installing WineHQ's wine-staging is that I guess maybe I don't know what esync is for since I don't notice anything "missing"/differnt/etc. and Warcraft seems to be working just fine for me for now.  They have scheduled maintenance again this morning to fix/patch broke things their lack of QA didn't find...  (2020-10-14)

**Comment by runboy93** [comment]
Now there is Lutris Wine 5.21, but yeah in my case it's much worse than 5.7.xx builds. Causes many problems on certain games, not for everyone but for someone.
