### ISSUE TITLE
Epic game launcher problem

### ISSUE THREAD

**Issue by Thouartfree** [lutris/wine#41]
Distorted screen, scratch screen or something
Hello guys. I am a newbie.
I install wine, install Lutris then install Epic game store form Lutris. When i open Epic game store, it comes out like this:

![Screenshot from 2020-09-08 22-43-38](https://user-images.githubusercontent.com/70966492/93000376-46131300-f552-11ea-968b-5b034370771b.png)

System information
Ubuntu 20.04
2 monitor
VGA: RX580

Is there anyone meet that problem. Is there any solution?
Thank for reading.

**Comment by lxmint** [comment]
I've a similar issue with the EGL but I get a black window.
This issue is only with wine 5.7.X but not with 5.6.2

System Information:
- Linux Mint 19.3 (18.04) and 20 (20.04)
- RTX2070

**Comment by tannisroot** [comment]
Recheck with 6.0-rc1.

**Comment by lxmint** [comment]
> 
> 
> Recheck with 6.0-rc1.

Checked with 6.0-rc1 but there's no improvement.
The EGL window is still black and the content flickers when you move the mouse quickly over the content.

**Comment by JanGalek** [comment]
try add DLL overrides `libEGL=n`

**Comment by lxmint** [comment]
> try add to DLL overrides `libEGL=n`

I've added this override in Lutris (runner options) but the content of the EGL still flickers.
