### ISSUE TITLE
Lutris Wine 5.21, WoW classic hangs during trying exit game

### ISSUE THREAD

**Issue by runboy93** [lutris/wine#45]
Happens with new Lutris Wine 5.21 version and with Wine Staging 5.21, not with older Lutris Wine 5.7-11 version.

Login to game -> after you in game try to exit from game from menu -> game freeze and after that whole computer locks up (not able to shut down normal way, have to go for power button)

Lubuntu 20.04.1 as OS, Lutris v0.5.7.1

Log during event:
https://paste.ubuntu.com/p/3fRdz8V37Z/

**Comment by runboy93** [comment]
Alright, tested few times it seems that also Wine Staging 5.21 also have this same problem after all, but it doesn't happen each time.

**Comment by runboy93** [comment]
Overall many problems with both 5.21 wine builds with blizzard stuff.

Also if exit from game is succesful with Wine Staging 5.21, after that blizzard launcher (battle.net) won't stop itself automatically, you need to go stop it manually from lutris.

**Comment by WannaBeOCer** [comment]
I don't play WoW but I noticed overlays are reporting Lutris Wine 5.21 as wine-4.11.

**Comment by LithianFI** [comment]
I am not noticing any issues when using Wine Staging 5.21, so I am not sure if the problem is exclusive with the Wine or somewhere else in the setup.

**Comment by runboy93** [comment]
> I am not noticing any issues when using Wine Staging 5.21, so I am not sure if the problem is exclusive with the Wine or somewhere else in the setup.

Did you try Lutris Wine 5.21, or just Wine Staging 5.21?

**Comment by LithianFI** [comment]
Installed Lutris' version of Wine just to test, still no issues when exiting the game. Using PopOS with Linux 5.8.

**Comment by runboy93** [comment]
Yeah got bored with WoW, so closing this.

**Comment by legluondunet** [comment]
I resolved this issue like this:
- use wine-lutris-2.21
- config WOW or other games with directX 11 legacy (see https://us.battle.net/support/en/article/56554)
