### ISSUE TITLE
Wine 5.21 blizzard battle.net cannot update

### ISSUE THREAD

**Issue by runboy93** [lutris/wine#46]
When using either Lutris Wine 5.21 or Wine Staging 5.21, blizzard battle.net cannot update itself.

It does show update bar, but then it disappear each time, when using Lutris Wine 5.21 or Wine Staging 5.21. Been trying to get battle.net update when using Lutris Wine 5.7-11, but it seems like update process is very random, it either happens or not, very hard to get logs for this problem.

**Comment by runboy93** [comment]
Same happens also with Lutris Wine 5.7-11, strange enough last Battle.net update (1.28.0.12476) came out without problems last week, but now for few days there seem to be new Battle.net update (no idea about versio number?), but it fails to update.

**Comment by thaewrapt** [comment]
Updated just fine on system-wide Wine-Staging 5.21 (I'm using a beta version of Battle.Net, though).

**Comment by legluondunet** [comment]
I resolved this issue like this:
- use wine-lutris-2.21
- config WOW or other games with directX 11 legacy (see https://us.battle.net/support/en/article/56554)
