### ISSUE TITLE
lutris-5.21-2 can not use CJK input method in WOW classic

### ISSUE THREAD

**Issue by wu-yue** [lutris/wine#49]
I can't switch to CJK IME in WOW classic with lutris-5.21-2

I did notice this with Steam Proton, but not on elder lutris Wine.

Currently, switching back to lutris-5.7-11

**Comment by SwimmingTiger** [comment]
The same issue for me. No input method can be activated in any game, application or even winecfg that uses lutris-5.21-2. It seems that the input method support is not compiled at all.

**Comment by SwimmingTiger** [comment]
And why I got an `wine-4.11-10841-g8dacc6b9027 (Staging)` with 32bit of wine???
![image](https://user-images.githubusercontent.com/4986069/100375242-72fe9e80-3048-11eb-8b5e-bb36f482f0a4.png)

**Comment by BorisCarvajal** [comment]
I can't even put an accent on vowels with my spanish keyboard.
Dead keys don't work in `lutris-5.21-2`, when I try to type `áéíóúü` the result is `´a´e´i´o´u¨u`.
Older versions and `vanilla wine-5.21` work as intended.

**Comment by wu-yue** [comment]
Just tried lutris-6.0-rc1, it's working greatly.

So maybe I should close this issue in a while later.

**Comment by BorisCarvajal** [comment]
I can also confirm that dead keys are working again in `lutris-6.0-rc1`.
