### ISSUE TITLE
Cossacks 2 Battle for Europe regression crash

### ISSUE THREAD

**Issue by qarmin** [lutris/wine#50]
When launching game, then it shows this error
```
Assertion failure (pos>=0&&pos<NValues):
file ../Classengine\dynarray.h line 98
```
![Zrzut ekranu z 2020-11-18 18-24-43](https://user-images.githubusercontent.com/41945903/99573776-cc2a5a80-29d6-11eb-9be9-7a6b53d9c370.png)

Wine staging and devel 5.21 works fine

**Comment by qarmin** [comment]
Any info why this is closed?

**Comment by tannisroot** [comment]
Because we now ship 6.0-rc1 by default.
