### ISSUE TITLE
Directx12 - game runs but the screen is black

### ISSUE THREAD

**Issue by nipnipj** [lutris/wine#52]
Hello!

I'm using Lutris 5.21-2-x86_64.
(maybe this issue is only related to this game)

After the installation of resident evil 3 remake, the game ran in directx 12 without any issues --- I ran the game, started a new campaing and I could actually move around Jill's apartment. I did not continue playing.
Then, I wanted to run the game again, but the screen just remains black. I could even manage, without seeing anything in the screen, start a new campaing and I can hear everything (even rain outside Jill's apartment) like when I started the game the very first time.
When I try to turn the game from full screen and windowed mode (by pressing alt+enter), I got a error message as shown in the attached image.
![Screenshot from 2020-11-23 11-21-04](https://user-images.githubusercontent.com/36553373/99989109-3bf66780-2d80-11eb-881c-ee411515fc5d.png)
Then game is set to run with directx11 api and works normally.
What can I do to play with dirext12? Is there a way to fix the directx12 error message? As I said at the very first time I ran the game, it worked. I literally checked video configuration and it was set to directx12.

**Comment by tannisroot** [comment]
Recheck with 6.0-rc1.

**Comment by nipnipj** [comment]
This game works fine when set to directx 11 and use lutris 5.21-2 with dxvk 1.7.2. RDR2 using vulkan api work fine with wine 6 staging.
