### ISSUE TITLE
Wrong wine version detected by Mangohud 

### ISSUE THREAD

**Issue by Snaggly** [lutris/wine#53]
Hello,
With the latest Lutris 5.21-2-x86_64 runner I read a wrong wine version on Mangohud as seen in the picture below.

![Screenshot_20201127_132640](https://user-images.githubusercontent.com/1353354/100451990-95300500-30b8-11eb-890c-3abeeaae1b55.png)
Regards!

**Comment by tannisroot** [comment]
fixed in 6.0-rc1
