### ISSUE TITLE
Weblinks broken

### ISSUE THREAD

**Issue by Snaggly** [lutris/wine#54]
Hello,
When a game tries to open a weblink it crashes. Previous Lutris-Wine build opened a weblink with my default webbrowser.

![Screenshot_20201127_134513](https://user-images.githubusercontent.com/1353354/100452243-096aa880-30b9-11eb-9e75-dde0cca1227e.png)

Regards!

**Comment by tannisroot** [comment]
What app is this?

**Comment by Snaggly** [comment]
The issue got fixed by Lutris-Wine 6.0rc1
