### ISSUE TITLE
enhancement: add scaling support for low res wine games

### ISSUE THREAD

**Issue by Askmewho** [lutris/wine#55]
Hi, I don't know how easy or hard would be that. but I would love a generic scaling support solutions instead of running 640x480 games on a window or changing the resolution to this resolutions. also, xBRZ would be really cool to have for.many low end classic games and would have a feature than counterpart windows retro gamers doesn't have. just an idea (as I am an xBRZ devoted). I know it's not an easy request. but maybe just think about it. thanks! also, we included lutris on RPI4 TwisterOS (due we have an x86 emulator with hw acceleration, box86, so we run wine with it).

**Comment by Askmewho** [comment]
what is that? place the repo please

**Comment by strycore** [comment]
it's the full screen scaling that is present in Proton. I think there's an issue currently preventing it from working on recent Proton versions. I don't what is the current status on recent lutris builds, I just know that on `nofshack` builds, it's disabled.

**Comment by Askmewho** [comment]
but it's open source? I use plain wine, not proton.

**Comment by strycore** [comment]
yes, it's open source. it's in lutris wine builds as well, not just proton. It's not in the regular Wine from WineHQ.

**Comment by Askmewho** [comment]
Ok, I will have to compile it bc the release is 64 bit only, stay this topic open anyway. thanks!

**Comment by strycore** [comment]
There is no open topic.

**Comment by strycore** [comment]
You're asking for something we already have.
