### ISSUE TITLE
Lutris Wine 5.21 and 5.21-2 removed?

### ISSUE THREAD

**Issue by runboy93** [lutris/wine#57]
I know this happened already like a week ago, but still asking.

Did these versions had overall many problems or what, for reason to be removed from Wine runners list?

Do you have plans to come back with regular wine versions, or are there still too many problems overall, compared to older 5.7-11 version?

**Comment by Oversomebody** [comment]
i compared some games like Spiritfarer (Win), Observation.  they favour 5.7-11 with ACO and esync enable, 5.21-2 performance is worse than 5.7-11 with ACO and esync enable, Neon Abyss and Ghostrunner is only able to run with 5.21-2,with 5.7-11 they will have black screen, and Ghostrunner doesnt have sound, only intro have sound.You need to pick and choose which version  is suitable.

**Comment by nipnipj** [comment]
Lutris wine releases are available [here](https://github.com/lutris/wine/releases).

**Comment by tannisroot** [comment]
Yeah they were removed due to various regressions, however now we have 6.0-rc1, which should work ok.
