### ISSUE TITLE
Media foundation and Lutris wine

### ISSUE THREAD

**Issue by nipnipj** [lutris/wine#60]
Do Lutris wine versions include media foundation support? I'm having issues when trying to reproduce the very first cinematic in Resident evil 7 (non-steam).

**Comment by kajlando** [comment]
Hey. Downgrade Lutris to 0.5.8 and try to run it with Steam Proton or Steam Proton-GE. Unfortunately displaying other versions of WINE has been banned :-1: in 0.5.8.1.
