### ISSUE TITLE
MultiMonitor Issue with switching to fullscreen. - Didn't use the primary screen

### ISSUE THREAD

**Issue by JokerGermany** [lutris/wine#61]
I wanted to play GTA V and got the same problem like here:
https://github.com/ValveSoftware/Proton/issues/4440

But it's even worse, because he opens even on startup on the secondary Screen.
> Ubuntu Mate 20.04.1
> if you use Alt+Enter to switch into window mode for doing something else and then switch back with Alt+Enter to fullscreen it opens on the secondary screen.
> 
> If you leave a game in window mode and you start a game, it will start in window mode. If you hit Alt+Enter it will opens on the secondary screen.
> 
> I didn't change anything, but there was a time, where i could drag the window to the desired screen, press Alt+Enter and it will be fullscreen on that screen. This didn't works anymore. It opens everytime on the second screen, which is on the left.

Bug didn't occur with Proton-5.9-GE-8-ST.
(Probably it would occour with the new Version Proton-5.21-GE-1!)

**Comment by kajlando** [comment]
Yeah. That's pity that Proton was banned from displaying in Lutris. I guess that I (and not only me) will have to stick with 0.5.8 unless displaying Proton become available again.. Unfortunately Lutris's now only open to the Lutris WINE versions. :-1:

**Comment by JokerGermany** [comment]
I am using Proton-5.9-GE-8-ST at the moment oO

**Comment by JokerGermany** [comment]
Yeah, i am using 0.5.8, but i think this bug didn't occur with prior versions of lutris wine, because i think it was a recent change in wine

**Comment by greggregm** [comment]
it may be the same thing when i boot up overwatch what i usually do is move it in windowed mode to the right screen then press fullscreen mode and then it ends up on the right screen.

**Comment by greggregm** [comment]
for what I have found online a possible solution that I found was from [Scaine](https://www.gamingonlinux.com/articles/setting-a-primary-monitor-for-launching-games.10352)  
the solution was to install arandr with the command:
`sudo apt-get install arandr`
after this run the program:
`arandr`
finally run xrandr to make the monitor the primary display
`xrandr --output [your name of your monitor]--primary`
if you cannot find the name of your monitor it will be found in the xserver setting if you have nvidia (e.g. DP-5 as shown in the image)
![image](https://user-images.githubusercontent.com/76880548/105030565-e2db4500-5a4b-11eb-9aec-2e19f4608c31.png)
