### ISSUE TITLE
WINETRICKS with Lutris wine runners not starting in terminal.

### ISSUE THREAD

**Issue by mixalis1987** [lutris/wine#65]
Trying to run winetricks using the lutris wine runners in terminal. However I keep getting errors over and over.
I also tried in fresh Pop_OS and 2 fresh manjaro installs and always get same error.

I am trying to run this:
`WINEPREFIX=/run/media/michael/LinuxGaming/games/novarotest/ ~/.local/share/lutris/runners/wine/lutris-5.7-11-x86_64/bin/wine64 winetricks -q dotnet45` is this not correct?
The error I always get is:
```
000b:fixme:winediag:__wine_start_process Wine TkG 5.7 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
001d:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
0009:err:module:__wine_process_init L"C:\\windows\\system32\\winetricks.exe" not found
```
The error is with all versions of lutris wine runners. 
Works with my system wine like normal. **Is it me and my command or a bug?** 

Thanks.

**Comment by liberodark** [comment]
Close is duplicated : #66
