### ISSUE TITLE
Winetricks not starting in terminal with lutris wine runners.

### ISSUE THREAD

**Issue by mixalis1987** [lutris/wine#66]
Trying to run winetricks using the lutris wine runners in terminal. However I keep getting errors over and over.
I also tried in fresh Pop_OS and 2 fresh manjaro installs and always get same error.

I am trying to run this:
`WINEPREFIX=/run/media/michael/LinuxGaming/games/novarotest/ ~/.local/share/lutris/runners/wine/lutris-5.7-11-x86_64/bin/wine64 winetricks -q dotnet45` is this not correct?
The error I always get is:
```
000b:fixme:winediag:__wine_start_process Wine TkG 5.7 is a testing version containing experimental patches.
000b:fixme:winediag:__wine_start_process Please don't report bugs about it on winehq.org and use https://github.com/Frogging-Family/wine-tkg-git/issues instead.
001d:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
0009:err:module:__wine_process_init L"C:\\windows\\system32\\winetricks.exe" not found
```
The error is with all versions of lutris wine runners. 
Works with my system wine like normal. **Is it me and my command or a bug?** 

Thanks.

**Comment by mixalis1987** [comment]
> Is not correct you to declare you runner as default with a little bash.

How would you do it?

**Comment by liberodark** [comment]
Something like that : 
```
WINE="${DIR}/${WINE_VERSION}/bin/wine"
WINE64="${DIR}/${WINE_VERSION}/bin/wine64"
WINESERVER="${DIR}/${WINE_VERSION}/bin/wineserver"
MSIEXEC="${DIR}/${WINE_VERSION}/bin/msiexec"
WINEPREFIX="My Prefix"
```

That just a example

**Comment by mixalis1987** [comment]
Hey, yea it's sorted now.
It was similar to your command.
I just did:
`WINEPREFIX="/run/media/michael/LinuxGaming/games/novarotest/" WINE="~/.local/share/lutris/runners/wine/lutris-5.7-11-x86_64/bin/wine" winetricks -q dotnet45`

And it worked running winetricks in lutris-5.7-11 wine runner instead of my system wine :)
