### ISSUE TITLE
Star Wars: Battlefront II Nvidia update driver error with AMD card

### ISSUE THREAD

**Issue by iMonZ** [lutris/wine#71]
Hey,
I'm currently using Ubuntu 20.10 with an 5.10 kernel and Lutris!
In Battlefront II (the EpicGames version)
I get this error:

> Detected NVIDIA GeForce driver version 337.88.
> The required driver version is 388.31 or later

The problem is that I have an AMD graphics card!
I started the game with this Vulkan ICD loader: radeon_icd.x86_64.json

**Comment by tannisroot** [comment]
I fixed this in 6.10 i think
