### ISSUE TITLE
[Regression] Unable to join multiplayer lobbies in Starcraft: Remastered on wine 6.0

### ISSUE THREAD

**Issue by ReDTerraN** [lutris/wine#73]
**Problem Description:** 
I can run starcraft remastered correctly.
however, if I turn on bonjour network on first battlenet click, I cannot connect any battenet channel (west, east, korea, asia).
If I turn off bonjour network, I can connect battlenet channel but cannot create or join a game.

According to user krokce it seems as the problem exists in the version lutris-0.5.8.1 and later. 

**Workaround:**
As of now all Starcraft:Remastered players needs to play >lutris-0.5.8.1 in order to play online.

**Summary:**
I dont know what has caused this regression but it seems to be related to the newer versions of Lutris.
Im unfortunately not a programmer so any help is much appreciated to see what change could have broken this.

For more information check following the thread: https://lutris.net/games/starcraft-remastered/

**Comment by ReDTerraN** [comment]
Sorry strycore, thank you for helping out sorting the ticket appropriately. Appreciate it!

**Comment by realmain** [comment]
I wonder if this is the same issue as in #56 . Though looks like [WineHQ](https://bugs.winehq.org/show_bug.cgi?id=50738) has a fix for that in Wine 6.5+

I hope that Lutris will release a new version sometime soon since we are still only on Wine 6.4 currently. I have the same issue with games that I try to connect via Zero Tier as well if I don't use `0.5.7-11`

**Comment by runboy93** [comment]
> I wonder if this is the same issue as in #56 . Though looks like [WineHQ](https://bugs.winehq.org/show_bug.cgi?id=50738) has a fix for that in Wine 6.5+
> 
> I hope that Lutris will release a new version sometime soon since we are still only on Wine 6.4 currently. I have the same issue with games that I try to connect via Zero Tier as well if I don't use `0.5.7-11`

Yeah, they seem to work for 6.1 instead (more stable?) than newer wine builds 6.5+

**Comment by tannisroot** [comment]
We have 6.10 now, closing
