### ISSUE TITLE
Add a patch for GTA V Online.

### ISSUE THREAD

**Issue by kajlando** [lutris/wine#76]
So currently GTA V Online redirects to solo session only.
A proper patch has been added to Proton-6.5-GE-2.
Would it be possible to add it to Lutris Wine to easily use it with Lutris?

**Comment by kajlando** [comment]
Try wine-tkg.

**Comment by kajlando** [comment]
Fortunately there are some solutions: wine-tkg with Lutris, Heroic Games Launcher (GUI for EGS) with Proton-GE/wine-tkg or launch from Steam with Proton-GE.

**Comment by GloriousEggroll** [comment]
There was no patch added to proton-ge. This seems to be a common misconception. The Origin downloads patch was found to be at fault, and therefore was removed from the build, which fixed online sessions. If this patch is being used in any lutris build for gtav then it should be disabled.

**Comment by SonicRoshan** [comment]
> Fortunately there are some solutions: wine-tkg with Lutris, Heroic Games Launcher (GUI for EGS) with Proton-GE/wine-tkg or launch from Steam with Proton-GE.

Thanks for your solution. Also, my friend got away with wine 6.9

**Comment by SonicRoshan** [comment]
I tried wine-tkg 6.8, and it works smoothly!!!!!
