### ISSUE TITLE
Star Citizen 3.13 Need Two New Functions

### ISSUE THREAD

**Issue by Ackurus** [lutris/wine#78]
There are no Lutris runners capable of running Star Citizen at the moment.
This pull request should fix that.
#77

**Comment by tannisroot** [comment]
Is this still valid for 6.10?

**Comment by Ackurus** [comment]
Star Citizen dropped the requirement for the SeekPenaltyPropertyQuery, and lutris-6.10-x86_64 includes the new QueryTraceA function which is still required (came from upstream). So these issues are closed. We're getting some hard to pin down intermittent crashes on start-up that doesn't happen on older patched runners (crashes happen with upstream wine too).

**Comment by Ackurus** [comment]
So, this issue is closed.
