### ISSUE TITLE
[Feature] Aspect ratio correction

### ISSUE THREAD

**Issue by FakeShemp** [lutris/wine#81]
When I run a game using Steam Proton in fullscreen, the aspect ratio is maintained. So on my 16:9 screen, a 4:3 game gets letterboxed with black bars on its side.

When running games with Lutris Wine builds, this is not the case; the game gets stretched to fill the screen. Is there a way to make the Wine build do the same thing as Proton.

**Comment by tannisroot** [comment]
Yes, just use the fshack version of lutris-wine.
Alternatively, enable an option in your monitor configuration that preserves aspect ratio when up-scaling.

**Comment by FakeShemp** [comment]
Thank you! That is just what I needed :)
