### ISSUE TITLE
Overwatch: randomly crashes after anything from 20 minutes to several hours

### ISSUE THREAD

**Issue by erilen** [lutris/wine#82]
**Description**
There have been reports from multiple people across Lutris forums, Reddit and Overwatch forums about Overwatch crashing randomly after what seems to be anything from 20 minutes to a few hours, with different wine versions seemingly crashing less frequently.

From these reports it seems like the crashes started appearing late April.

Common points
 - Log files does not seem to produce any meaningful information.
 - It does not crash immediately after starting. I can personally play often two or three games before it crashes.
 - It does not seem to matter if you are in a game or at the menu. Idling at the main menu will still crash the game after a while.

**What has been tried?**
Wine versions tried (all produced the crash): lutris-6.0, lutris-6.1-3, lutris-6.4, wine-tkg 5.22r2, wine-tkg 6.8
 
DXKV versions tried (does not seem to have an impact): 1.7.1L, 1.7.3L, 1.8.1L

Audio systems tried (does not seem to have an impact): PipeWire, ALSA, PulseAudio

**Workaround**
Downgrading to lutris-5.7-11 seems to work for everyone who reported the issue.

Lutris forum thread, with reports and log files: https://forums.lutris.net/t/overwatch-exits-during-gameplay-black-screen-to-desktop/12584

Opening an issue here hoping we can pinpoint it further and eventually get a fix. Any help gathering info is appreciated. And apologies if this is not the correct place.

**Comment by tannisroot** [comment]
This is fixed in 6.10
