### ISSUE TITLE
Futex2 enable on Lutris Build ?

### ISSUE THREAD

**Issue by liberodark** [lutris/wine#98]
Hi,

On wine-tkg futex2 patch is applied but on lutris i dont see any futex2 patch.
But dlls/ntdll/unix/fsync.c have futex2.
So can you add / enable it if is not applied ?

https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-patches/proton/fsync_futex2.patch

Best Regards

**Comment by tannisroot** [comment]
It is applied, check wine-tkg.log

**Comment by liberodark** [comment]
yep good thanks for confirmation
